name: main-ci

on:
  push:
    branches:
      - x

jobs:
  build:
    runs-on: self-hosted   

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:v1.${{ github.run_number }}

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull exact version
        run: |
          docker pull "${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:v1.${{ github.run_number }}"

      - name: Stop & remove existing container (if any)
        run: |
          NAME="${{ github.event.repository.name }}"
          if [ "$(docker ps -q -f name=^/${NAME}$)" ]; then
            docker stop "${NAME}"
          fi
          if [ "$(docker ps -aq -f name=^/${NAME}$)" ]; then
            docker rm "${NAME}"
          fi

      - name: Run container on port 4000
        run: |
          docker run -d \
            --name "${{ github.event.repository.name }}" \
            --restart unless-stopped \
            -p 4000:80 \
            "${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:v1.${{ github.run_number }}"
